#!/bin/bash

function decode()
{
  echo $(TIMEFORMAT="(%3U + %3S)" ; \
       { time python2.7 decode -s $1 -k $2 1>$3 2>/dev/null ; } 2>&1) \
       "* 1000" | bc -l
}

function compute_model_score()
{
  python2.7 compute-model-score < $1 2>/dev/null \
            | grep -o "Total corpus log probability (LM+TM): .*" \
            | cut -d' ' -f6
}

ss=(20)
ks=(10)

cur=0
tot=$(echo "${#ss[@]} * ${#ks[@]}" | bc -l)

for (( i=0; i<${#ks[@]}; i++ )); do
    for (( j=0; j<${#ss[@]}; j++ )); do
        k=${ks[$i]}
        s=${ss[$j]}
        conf="output.s=$s.k=$k"  
        echo $conf >> try-parameters.log
        decode $s $k $conf >> try-parameters.log
        compute_model_score $conf >> try-parameters.log
        cur=$(( cur + 1 ))
        echo "$cur / $tot * 100" | bc -l | xargs printf "\r%-3.f%%"
    done
done