#!/bin/bash

function decode()
{
  echo $(TIMEFORMAT="(%3U + %3S)" ; \
       { time python2.7 $1.py -s $2 -k $3 1>$4 2>/dev/null ; } 2>&1) \
       "* 1000" | bc -l
}

function compute_model_score()
{
  python2.7 compute-model-score < $1 2>/dev/null \
            | grep -o "Total corpus log probability (LM+TM): .*" \
            | cut -d' ' -f6
}

ss=(1 5 10 50 100 500 1000)
ks=(1 5 10 50 100)

cur=0
tot=$(echo "${#ss[@]} * ${#ks[@]}" | bc -l)

for (( i=0; i<${#ks[@]}; i++ )); do
    for (( j=0; j<${#ss[@]}; j++ )); do
        k=${ks[$i]}
        s=${ss[$j]}
        conf="$1.s=$s.k=$k"  
        echo $conf >> "data/$1.log"
        decode $1 $s $k "data/$conf" >> "data/$1.log"
        compute_model_score "data/$conf" >> "data/$1.log"
        cur=$(( cur + 1 ))
        echo "$cur / $tot * 100" | bc -l | xargs printf "\r%-3.f%%"
    done
done